### ISSUE TITLE
0.7.6-nbxyz2 version fails to start on Synology NAS (dnsmasq permissions)

### ISSUE THREAD

**Issue by andrew-potachits** [netbootxyz/docker-netbootxyz#93]
took latest version 0.7.6-nbxyz2 and it failed to start on Synology NAS Container manager. The errors are like this:

```
netbootxyz  | [init] Setting up user nbxyz with PUID=1000 and PGID=1000
netbootxyz  |             _   _                 _                      
netbootxyz  |  _ __   ___| |_| |__   ___   ___ | |_  __  ___   _ ____  
netbootxyz  | | '_ \ / _ \ __| '_ \ / _ \ / _ \| __| \ \/ / | | |_  /  
netbootxyz  | | | | |  __/ |_| |_) | (_) | (_) | |_ _ >  <| |_| |/ /   
netbootxyz  | |_| |_|\___|\__|_.__/ \___/ \___/ \__(_)_/\_\__,  /___| 
netbootxyz  |                                              |___/       
netbootxyz  | 
netbootxyz  | If you enjoy netboot.xyz projects, please support us at:
netbootxyz  | 
netbootxyz  | https://opencollective.com/netbootxyz
netbootxyz  | https://github.com/sponsors/netbootxyz
netbootxyz  | 
netbootxyz  | [start] Starting supervisord (programs will run as nbxyz)
netbootxyz  | 
netbootxyz  | /usr/lib/python3.12/site-packages/supervisor/options.py:13: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
netbootxyz  |   import pkg_resources
netbootxyz  | 2025-06-14 16:56:18,875 INFO Set uid to user 0 succeeded
netbootxyz  | 2025-06-14 16:56:18,879 INFO supervisord started with pid 1
netbootxyz  | 2025-06-14 16:56:19,882 INFO spawned: 'nginx' with pid 22
netbootxyz  | 2025-06-14 16:56:19,883 INFO spawned: 'dnsmasq' with pid 23
netbootxyz  | 2025-06-14 16:56:19,884 INFO spawned: 'webapp' with pid 24
netbootxyz  | [dnsmasq] Starting TFTP server on port 69
netbootxyz  | [dnsmasq] TFTP root: /config/menus
netbootxyz  | [dnsmasq] TFTP security: enabled
netbootxyz  | [dnsmasq] Logging: enabled (dhcp and queries)
netbootxyz  | 
netbootxyz  | dnsmasq: failed to create listening socket for port 69: Permission denied
netbootxyz  | 
netbootxyz  | 2025-06-14 16:56:19,905 WARN exited: dnsmasq (exit status 2; not expected)
netbootxyz  | 2025-06-14 16:56:19,912 WARN exited: nginx (exit status 1; not expected)

```

the compose file is this:
```
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.47 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 3000:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
```

rolled back to 0.7.5-nbxyz9 and it works fine.
